### ISSUE TITLE
SNMP input: questions of the reuslt 

### ISSUE THREAD

**Issue by linghuang1** [logstash-plugins/logstash-input-snmp#14]
Part of result is as below:
{    
......
"entityMIBObjects.entityPhysical.entPhysicalTable.entPhysicalEntry.entPhysicalMfgName.21914":"Cisco Systems",
"entityMIBObjects.entityPhysical.entPhysicalTable.entPhysicalEntry.entPhysicalMfgName.21659":"Cisco Systems",
"entityMIBObjects.entityPhysical.entPhysicalTable.entPhysicalEntry.entPhysicalVendorType.21849":"1.3.6.1.4.1.9.12.3.1.8.29",
......
} 
And my questions are:
1. What are the numbers 21914, 21659, 21849 mean? how can I strip it, as there has a lot of duplicate data.
2. For some OID fields the value is another OID code, how can this happen?

**Comment by axrayn** [comment]
The number at the end of the table entry OIDs, e.g. entPhysicalEntry, entLogicalEntry, etc. is the table index number for that particular entity.

For each of the leaf nodes under entPhysicalEntry (entPhysicalDescr, entPhysicalVendorType, entPhysicalContainedIn, etc), there should be a corresponding walk result for each of the index numbers. That way you know when you're referencing various OIDs, you know you're getting data from the same physical entity.

This means that when you're looking at snmp walk results there should be:
entPhysicalDescr.21914 = "SomeString"
entPhysicalVendorType.21914 = .1.3.6.1.4.1.9.something
entPhysicalContainedIn.21914 = 1001
and so on.

For the results that are OIDs themselves, this is because these particular values require looking up in a MIB file list. For example, the power supply in my Cisco 3750 Switch returns ".1.3.6.1.4.1.9.12.3.1.6.95" which, when looked up, translates to: "iso.org.dod.internet.private.enterprise.cisco.ciscoModules.ciscoEntityVendorTypeOIDMIB.cevMIBObjects.cevPowerSupply.cevPowerSupplyAc465W"

Hope this info helps.

**Comment by colinsurprenant** [comment]
Thanks @axrayn for the explanation. 

@linghuang1 so yeah, as you can see we haven't implemented any specific support for MIB objects like tables yet and IOD references. 
The [first release roadmap meta issue](https://github.com/logstash-plugins/logstash-input-snmp/issues/2) list the implementation priorities, if you think something is missing don't hesitate to open a new issue.

I will go ahead and close this issue as I think the OP question was correctly answered, please feel free to reopen if you think otherwise.
