### ISSUE TITLE
Default output and ECS

### ISSUE THREAD

**Issue by axrayn** [logstash-plugins/logstash-input-snmp#47]
At the moment we're using the 'host' field to show the host address that was passed into the input from `%{[@metadata][host_address]}`

To conform with ECS, should we check if an IP was passed and then store it in either `[host][ip]` or `[host][name]`?

**Comment by colinsurprenant** [comment]
Yeah good point for ECS - I'll table this for now-now and will have to look at it globally for sure.

**Comment by colinsurprenant** [comment]
@axrayn just to expand a bit on that; we are trying to come up with a consistent plan for ECS in logstash, for example providing BWC etc ... since this is an initiative that will impact lots of plugins. Once we have a better idea on out strategy I'll circle back here and we can see how to move forward with it.

**Comment by swtrux** [comment]
I ran into this issue today and added the following mutate to conform to ECS.
mutate {
    rename => { "host" => "[host][ip]" }
}

This format should be the default for host in the SNMP input plugin.
